name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variable
      run: |
        SHORT_SHA_COMMIT=$(git rev-parse --short HEAD)
        echo CONTAINER_RELEASE_IMAGE=registry.gitlab.com/akachain/product/aura-network/front-end/landing-page/${GITHUB_REF_NAME}_${SHORT_SHA_COMMIT} >> $GITHUB_ENV
        echo REPO_MANIFEST_NAME=aura-network >> $GITHUB_ENV
        echo REPO_MANIFEST_URL=git@github.com:aura-nw/gitops.git >> $GITHUB_ENV
        echo REPO_MANIFEST_BRANCH=master >> $GITHUB_ENV
        echo REPO_MANIFEST_ENV_DEV=./clusters/k8s-dev >> $GITHUB_ENV
        echo REPO_MANIFEST_ENV_MAIN=./clusters/k8s-uat >> $GITHUB_ENV
        echo REPO_MANIFEST_TAG_IMAGE=image_landing_page >> $GITHUB_ENV
    - name: Build the Docker image and push it to the registry
      env:
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      run: |
        chmod 777 -R ./ci
        ./ci/build.sh
    - name: Update manifest
      env:
        SSH_KEY_GITOPS: ${{ secrets.SSH_KEY_GITOPS }}
      run: |
        ./ci/updateManifest.sh
